Update PresentationTopics
ArsenEloglian/AdvanceProgrammingTechniques_2223 pull request #171
Opened 2022-11-18 19:27 UTC by Admarx

Dopisanie się na listę do pozycji piątej - "Stosuje techniki śledzenia aplikacji".

2022-11-18 19:30 UTC, MateuszSapala submitted a review, later dismissed

2022-11-18 19:40 UTC, Wegrzynk submitted a review, later dismissed

2022-11-18 19:53 UTC, ElizaWielocha approved these changes

2022-11-18 23:26 UTC, ArsenEloglian requested changes

2022-11-18 23:26 UTC, ArsenEloglian commented on PresentationTopics.txt
> -# <Imie_Nazwisko>
please uncommit or revert this line change

2022-11-19 10:26 UTC, Wegrzynk approved these changes

2022-11-19 11:08 UTC, ElizaWielocha approved these changes

2022-11-19 14:30 UTC, MateuszSapala approved these changes

2022-11-20 16:13 UTC, Admarx commented
@ArsenEloglian could you review again? Changes have been made as requested

2022-11-20 23:34 UTC, ArsenEloglian approved these changes

2022-11-20 23:54 UTC, merged