Develop
ArsenEloglian/AdvanceProgrammingTechniques_2223 pull request #3
Opened 2022-10-14 15:28 UTC by KaroW97

2022-10-14 22:20 UTC, ArsenEloglian approved these changes

2022-10-14 22:24 UTC, ArsenEloglian commented
Please update attendance list

2022-10-21 15:42 UTC, barbara-k97 submitted a review, later dismissed

2022-10-21 22:48 UTC, ArsenEloglian requested changes

2022-10-21 22:52 UTC, ArsenEloglian commented
Please revert unnecessary changes.

2022-10-24 09:29 UTC, ArsenEloglian commented
@KaroW97

2022-10-24 14:49 UTC, ArsenEloglian commented
@KaroW97 
Please revert unnecessary changes and resolve conflicts.

2022-10-27 08:40 UTC, ArsenEloglian requested changes

2022-10-27 08:40 UTC, ArsenEloglian commented on AttendanceList.txt
> +
Please revert unnecessary changes

2022-10-31 11:31 UTC, ArsenEloglian commented
@KaroW97 
what is the status of this PR?

2022-11-15 16:44 UTC, ArsenEloglian requested changes
The commit message is not in alignment with code diffs.

2022-11-18 15:35 UTC, Flehmango commented
@KaroW97 closed due to inactivity. If needed, please open a new PR

2022-11-18 15:35 UTC, closed without merging