Completed 14.10.2022 tasks
ArsenEloglian/AdvanceProgrammingTechniques_2223 pull request #9
Opened 2022-10-19 09:27 UTC by Wegrzynk

2022-10-21 11:49 UTC, ArsenEloglian requested changes

2022-10-21 11:49 UTC, ArsenEloglian commented on Kacper Węgrzynowski/MiddleofLinkedList.cs
> +}
please add endline here

2022-10-21 11:49 UTC, ArsenEloglian commented on AttendanceList.txt
> +*/
please add your changes below of */

2022-10-21 16:06 UTC, Wegrzynk commented on Kacper Węgrzynowski/MiddleofLinkedList.cs
> +}
Pushed a new commit fixing this issue

2022-10-21 16:06 UTC, Wegrzynk commented on AttendanceList.txt
> +*/
Pushed a new commit fixing this issue

2022-10-21 23:02 UTC, ArsenEloglian approved these changes

2022-10-22 08:57 UTC, markow1997 approved these changes

2022-10-22 09:50 UTC, Wegrzynk commented
@ArsenEloglian I have similar problem to @WashingtonD in that i cannot merge this PR, because 4 of the older commits are unsigned. git commit -s doesn't seem to work. Should i do a rebase to sign these older commits, or is there a simpler alternative?

2022-10-22 09:58 UTC, ArsenEloglian commented
> @ArsenEloglian I have similar problem to @WashingtonD in that i cannot merge this PR, because 4 of the older commits are unsigned. git commit -s doesn't seem to work. Should i do a rebase to sign these older commits, or is there a simpler alternative?

My proposition is to close this PR, create a new branch from the "main" branch and commit using flag -s (please remember to configure git before starting work with git:
git config --global user.name "FIRST_NAME LAST_NAME"
git config --global user.email "MY_NAME@example.com"
)

2022-10-22 10:41 UTC, closed without merging